# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '5ed925c0fecc49d4c0ee9bf57becb860'
  config.secret_key = '6155b78cae594d72e9415695c13800c2'
  config.default_from = 'ileceis@msn.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
